language: python
virtualenv:
  system_site_packages: false

python:
  - 3.6

services:
  -  postgresql

before_install:
  - cd django/congressionaldata
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export DJANGO_SETTINGS_MODULE=congressionaldata.settings.dev

install:
  - pip install -r requirements.txt -t lib
  - pip install coveralls

script:
  - ./manage.py test

after_script:
  - deactivate
