language: python
virtualenv:
  system_site_packages: true
python:
  - 3.6

services:
  -  postgresql

before_install:
  - cd django/congressionaldata
  - export DJANGO_SETTINGS_MODULE=congressionaldata.settings.dev

install:
  - pip install -r requirements.txt -t lib

script:
  - python manage.py test
