language: python
virtualenv:
  system_site_packages: false
python:
- 3.6
services:
- postgresql
env:
  - DJANGO_SETTINGS_MODULE=congressionaldata.settings.local

before_install:
- cd django/congressionaldata
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
install:
- pip install -r requirements.txt
- pip install -r requirements.txt -t lib
- pip install coverage==4.5.1
before_script:
- psql -c "create database ${LOCAL_POSTGRES_DATABASE_NAME};" -U postgres
script:
- coverage run --source='.' manage.py test election_data
- coverage report
after_script:
- deactivate
