nguage: python
virtualenv:
  system_site_packages: true
python:
  - 3.6

services:
  -  postgresql

env: # => 4
   -DJANGO=2.0.3

before_install:
  - cd django/congressionaldata
  - export DJANGO_SETTINGS_MODULE=congressionaldata.settings.dev
  - virtualenv env -p python3

install:
  - pip3 install -r requirements.txt -t lib

script:
  - python3 manage.py test
