language: python
virtualenv:
  system_site_packages: false

python:
  - 3.6

services:
  -  postgresql

env:
  secure: "IwfVT7C39/bn95s2p4e/YyYjVy1pGmXs59p8c5ppMPvkghBNues7Yk6D36pW8+3Xy4XRatr/b2Xo1jMxrbM+29sYxBDgYvK2rQAhQ4N3CTvtd9nvb9GRCHMil4E6z9SACUNCwzH/Qk2T32po3RBeHwRpL2PsdDr281GCxlMjojbvFqNN82GH6sQ1rFhg2bn/uAynJ3DvNaA8MLh/eCZ4jmMeW96FTDmV3+bTMvwZTejZWSYJmCfGOgMJ0fEFDeC6pcJwsE2avd1Odfzq6SypP0KYOhzTtaMvjAJy1AWay1MlsZiVuRUVdxuhTNcA1V9xhHyA95m9Ey/H4qu5DUZh8TqMIeuc0llqcVHWUn0vfVbT74OB/EYLzvDFgf4Cu+0pVZvPRzlZoFvCfrn0+e5jlPj354GsqxtCkDF+EtxPy4CjVcE6WEjfo20KuVP4CRdsZjhs92DYZMKI0pShQT005Nn3gG2Qvr8eZzy4xk9G4g+4KinJLZLvEbfOZNc1Uw7zrkHY9i5qxvX8OAjTOaraRkVcoSzKs6hoftztcVEmXviMNrbFN03Y5HRP5gXH3hxHfqNdfWzj8mr76fjEL/ZigfqtaxiC3l038xJOKYSuI9+fbO2GQwfxbzLqOD/syuWyCAW+XHImf8uQHA5x7lVg53s/8fVGpD8/93XCMPNS62U="


before_install:
  - echo "Attemptint to echo secret..."
  - echo "$SOMEVAR"
  - cd django/congressionaldata
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - export DJANGO_SETTINGS_MODULE=congressionaldata.settings.dev

install:
  - pip install -r requirements.txt
  - pip install -r requirements.txt -t lib
  - pip install coveralls

script:
  - ./manage.py test

after_script:
  - deactivate
