language: python
virtualenv:
  system_site_packages: false
python:
- 3.6
services:
- postgresql
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=congressionaldata.settings.local
  global:
  - secure: nATX9N14homMRJt6JfMy2hjqCj9LUs+qRE/9xgEexi33t7OVut1els5ndGXHYPUSRjn3mDyZErLkgOiZkDP8/6qoJvHPbFZImtfVhQpYNFkr5UK37e+3db8SJ12lctAlne6G/fmuPCXp1mPEXQD2aMwkB8HGFA93jP/xAXfp/ravMH93Teml37AbXfSV9Ug9EPSTlMoEO1K7M9aq3DRFhHJ8TSJTbAcEGS/HyS225n8WwM3d17vJDZVxaRMB5SSZXU/1HSd+TE0KMGdLDpYUH/0QqLnQXTD19NwaHR518EXJTjajQEahNNLlnmu0X+C4DrEL995gyUnWyXI5suu7kAsSqmmzovhxvxLjAKrx+1zGhHveYekaekWbVmBBpiL8GXritaBUnTki1SJ7UfbyviPLMl/Q39bqTNZcDHLfKSGMW82giKHorqfZvSYR1c+d7cQnM6fzOsIjTGZiJmkQxuyU+WJleK07CjQuwPd7hTxs6UBJXwjzrdZcfYQTo5NPBbz3Y6WZfhUiKL3Enrd0B9xxaOstv5k4/BbOppRnIfteRrWmG6HsIJToCRyEqMyXOxpiPAnEc6/jncS7UIf91ROVaCB/2A+qDPOAONvkTUnIJJL5oLz5jRfKelsC6JNvZ19YTdUOurrSok33DPlEu5uP5EIhyfXsHiCx7c9L7ZQ=
  - secure: AvvwP8Y0Fl0O3PrSvocVaImqX/Jnu1VFkR3eGPmTZu1fnNg3lIO2w/x6obVqVzoJultN1/F7Q12+vKhxbiRz9xCIFL4Zb00URealRPKZ7dpANZ49xytKvc5GXwyGn5EXTcIXkxlCil0t/jUZgpyyiB99/cFpInFKuTyg53mLrQ8DEySOC2s+8mh15Jm9STWIqE2k/+Lk1S3VEEIYjs4PohaqqlyYObjO4SgDgzHVonYBNGAX5Wv5D36uXtFv82HVB9sa2puvW8gTJEb8HY/9NZ6AQRSOU4HX6ZcDg4LfZU0DgatLFRNeQmRHGr2aqYjY6AUtDL/15wJzLmkOHoKr1UfMuXaOiEOZyRX3JKB+TvwBNurXDlyEZ44HC6veaoYKLD394VU2iv4P6SoZZ4eNUxSbIKDSd7HG76COtKjCvsyVxhQO4i2H8AYVCyAUfeWW52Cu6JYUojaYb7x6Pco8h7TckKIoNh5nsCK2RMRidNIKPHAzzSTwbrx5zCNsvQKn90bOm/qwn/T4qliS881tTCpCKriClVZaIVi7s7r7sXdUVBCcEmsBcO87osBMUgrfigwbJ8GghCjfpOpv+Y9SfFovoziLI+WSnXQw6MoNqX42LP0PHFFBMOBdhtID5T8UTdayA4c20wCveXSVTx8fh1PxAjeADJHR08LFuNm0CF4=
  - secure: h3cd6H5U0llXDSh5nD3y7tPjj2yU3/mA5EIaKauNFWgN3sfjRxqmjKmvrjVyVxN5eM3C+ALMKY0Rkavr1NqaDe1/XJOgEDCnOKjc75gCtrn2j01s8/hszNRCjjGJqJ2uo3ettDgdqrhLx9/29ch7xUoLiCySxFos/W90XA9MB0gHwlospEiBDxa5DIJpbKeetZoJKHENKJf9ft16LV2bftkks+cGMn69x+HQxcE0GSPA8NcMveHCz5vYVgnhhK8sK//gzWfxtsqIwG3+/a5ulemeT/LZWeSsvx2BUvNRbukRMjFuIOmmEAvwzmaf9Y4s37yLMr9wuebZ3O+e5XJgwdKpr8pgXsmYW0SdZxENq6dWL7fMPTI6oh1voME7y/JU8uCnOSm4NaVgAOi99OMEGojF/1aM0wNyXj+j8a0sPJARZ8nQLuyna27iTvO/sfmFnrfbnbxNsropNfd9G+UAECY+ixlWuyV7tmijbJph71q6DUMZ2Ja0nK3IJQRo72tjar1nJeifdX0tQDlT24Vpi38Lj82qxHgnewv/5oKE5Wi+c5WYo0EpAIfvxC2mMJGyMPwU9P/MMR6bNntyVtlUC0KMpQExg2cK5DX6jwP5nPWDPXHbzBslKTX18GfAQ9JJAG+QpK1uDErMWY3Ynb5XQmndNUHrriIgq3gVVDXyNLs=
before_install:
- cd django/congressionaldata
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
install:
- echo "$LOCAL_POSTGRES_DATABASE_NAME"
- pip install -r requirements.txt
- pip install -r requirements.txt -t lib
- pip install coverage==4.5.1
before_script:
- psql -c "CREATE DATABASE ${LOCAL_POSTGRES_DATABASE_NAME};" -U postgres
- psql -c "CREATE USER ${LOCAL_POSTGRES_USER} WITH LOGIN PASSWORD '${LOCAL_POSTGRES_PASSWORD}';" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON DATABASE ${LOCAL_POSTGRES_DATABASE_NAME} TO ${LOCAL_POSTGRES_USER};" -U postgres
- psql -c "ALTER ROLE ${LOCAL_POSTGRES_USER} CREATEDB;" -U postgres
script:
- coverage run --source='.' manage.py test election_data
- coverage report --omit="*venv*","manage.py"
after_script:
- deactivate
notifications:
  slack:
    secure: PS3gjL6QJlqrkl82Uos+jAtC/AKpP2bKIpe/fXjcJdDIPNAdIOfsrP/JJ/PnuFt7cmo9cDGKJzpzB3ODx6Hz6rxvodr041Vt/43mEfngb4sMGunbX07Z+vLnSAydS70DB9g+g5kbAVd7Cp2Y0HAc2VwYma6bGzhkqRWYeSv2s/uCQTfyTFhOjjr4w1nG/tZGXL571/3ULMo3JEnS3qhHlxPoSAkCnH0c9OEg9u0v4KPKmc4Nv0pVeCQQ3hQiEqxPKdwUNBRsTn1sMXXIJ6vOBsCwwNJY48Omz2sU7NnIASlWasFjhLhBm3qG9+kzLeerGDyI/nChiR50Jn6WlIX81gzpCaA+DCquAmTMOhaicymfaEMe3Wi/OmovgrXBBRZ8ncozexL9Ig5LkqiQ4a1ue2oamwhViOF2Tbr5qkfgqqqXYH3d5Lajdx0LUDXh1Wift9wDlw74xhjI/T7/g/FDNHk5XudJv8R16eikkyHjsZZjLnUYMA3ctYEnIRiodLtwVTfbNuW8pOpkhBTiJfcsVNZYd3NazUpnv4WXjcc6jSpMsmdVMUV6LEEBgsdAJCvty/LDNdJkDFna4gAy7Y/uHMygzxaSNKz6Ti20tzOKXwaT/TUfevTrm7Xldtn4//vt5cND6NxWldf4aeRZDlkOIBem1htZT8VyFI4ynxu7YSE=
