language: python
virtualenv:
  system_site_packages: false
python:
- 3.6
services:
- postgresql
env:
  matrix:
  - DJANGO_SETTINGS_MODULE=congressionaldata.settings.local
  global:
  - secure: n5saGmKAySpXPIkmWmJBV3EJTvd424x6ufJTHzhVjh0wCiWE2zpNaqFOhZBYLoMFZicz182pQ5crHjWScHV2I84hxpfhwpD4H+k8PqkJcmu1v6+bOeybYsKpbHb0Zh67DrJirTJVIzZltjzVM8PReHsdjhPLPrLlBccI6MKVBWdHlK++z+NcfYdWYprbSn+HRslyLOC96TLrtprxTRTruEOdKh1N9iD9PQrfU5ACvr3KHNLSaufN3RNdII7uTBcBYKL+cHrbvcEpZChL0cFn4r+EhcRqJqeaCLMTgfoxklY0rHhNF/rDa2nITFWkFYI5kTVOcK9+gnh/vErVu5WtcCRMgPdIy6SIKvfkhCGzjrvGWmN5a0iesbbWHpc11xN6PlupaF+GAIvOUie60mYflVRY4naoMikCcXkhWMv0Bidnl14JXYOXWBAEC8XLyrIIe42aSKHtGebbKO1u4SC0sPXRCBodaHrJey1yYWgDgLx/D4aE1mFWqNwFgOiwoX85lD5qsTv9LhMEdYwZq4mHaIXBK2li5Ini+MYZw+pYF4hp3EBPAQtnd3LcFRrAqg67NOwPDU3G9dODASYmELcStZ7YIUKZzbI6tLd77JG/6uciGl5pYZHaoSxREWuYl8ckGiy+P+y1Q/N6dTvyAIfWqiFYMEb7uMEJSmPASYlwRYM=
  - secure: ygxEvr+mua6k1aokvuGn2S++Qa/FqXmFmSDd0ixCc1w448eh4lw/kyxzeI23vObzGVMVxlBVDexiLQG4ATNrHjimSGDqJVtIxxe3cfr7sijzp5Od6TdMjGGvobyFOvz6kQ2pcE2GMcKEFiO08iLJXy2XVWxqoBM8E0yHG0WmPjtFv5uL4GhA6p8VnqqrcWK8LST2PIb+7uq7xHrsv1IyvqPGQJT0xHryNGMPfGtFYBGrWxRHoJNw6u6+pbA+FaMgjLkvcuzdFsziGBx74GIh1jrfV9mWLeMVMOUwUS8FQIjH5Rc9aruo3JTDW+Zri8a1S0V8PiTg6B/sBo+b79R3PA73yKwmijrQIzkt2RDu6YPMz/1UdzmvgC5YNbG00R8abod8AwmDd+2uwci3945EJByGRuY6I5NHI/xBS4tOuFm53L3GNYTaZ2j3zVKC9XJNxjEA0Vq1zgMfm2NLjaAGOuLMn/sSlopgvH54i9BcKB88i0HLYehsA/DdOWRaG76DG5/DqKupnxOuwI9KoiD7YwVikBtJsl4EZtvDdZjB5xuMnItJauCMJooNPz2/hBFbmEqqtdw7n14DlxA2I877hsIjF6BNPR9zbk3Wbmc3ypGu7LgZKE8iQM9tkTz70CeJlT9oZuvD0oLW1BO8frfhb7ZYJgdzDASiT/peB3FEiIQ=
  - secure: eydEVlswKAgkiMzvHB9oiOfeUPlJzxaRSQacygdRxRTiwCpXTomANbHyjVbmjG6Tu3N0w8WLqu/3OPmJFZLdQOw+3twO4OTaU3Eudk+bGRWb0YhG73pBNJwzq3YS48yrvbLW5m6FpITjlubg+vH+MMvYLdqUc+i2TgaCmt5aNhikOf93Iu81HO7RdMpcv3qMT6vlPPgN5NOFQ+y4Uwd8KBhBp1kOt22C/JnCs/9pBCI/qQnxo1MyFs3moM8jAeNuEwooJHsK/Pn8IRstWEGc0SmDZhPlglLmSqmvKN9cLtvna6KSuE1oiBxxMHVQtj3Rs9rr4ook+xsLkyQlxHUj+/ZqGHMknCpD0yP4RalNBZru78mhAXsIjHrrIK1EGbo71QL4x+C7A0aGKImOEvK14hRCh9PDyNCtMCq94hvGwE8rXkuI9CyZw+e+V6BuJEtyW3J5aJ7iPOHsVZULUZvn5Vwd7PPoqqAAZAkSPqTVgwa3362p4AKNdapZKygYsgYvcbXVgG/Y8b/u44g1p/2h2b4XiVN3z9E5PX4RjrrBWCKSv1RXs2FHXWbw2Nun+MckCfGRKGCzbnxjp3XfDrRY0qJwTCh1gt4bo8GAwm25WFNvsDaK2PC45Jm4TkIjihMNmph6EZwrVZsSLTiYYxoL6Sn9CT51qa9WouK4k8dvfqI=
  - secure: QKpBEws9P5b+JVkARaq3plIaCO3KqNWOq+fySDzmMAilJtqWur36LF5Cocvc4Pu7Jqv6XWfjC7hyItuUA2v9i6jAQtCDqstlSc25g3Z1kGpSrZz8dodUm4gMJEKZIuuAeoepP3UcyKphCr28StF3GKc4vCrK48eSO8Che3nenuqfxucOUTHU+hFuagIOhciFqx23gvc9P3s7jqFYezElz/n+4BrDzPvHs1+Up6pgcSC3oq/j5+5W3j+UXbis/WYfxDf26WeUDSRoHJzp5mcoF64ZDF6NeNTdGuBHNkp+G/ClytSPbGIFWguHUp98aJFtkgQzl/XICPYznkYWRFbXE+sBqKW2y2YXnCDtgCyGt0voI0w3ZDvHmkzZm/uXnMnURG9tZmDUjWQfLL7pGVzUyntJIhwFGtccJhdE1PKWDnCc3IY1FDld4CUg0gBv6rIKwd39TT8RR6yyum3l/O9G1ssaESNQy5/6iXNRCPsrJ99zQW3VHKp75z6nv+cD50nblkY9aQ2mqjseQkYjrkViVwxhqmfNDBP8ZHeJMAWQ9+/wD5Ad3vd+3q9LCoLi2ZFHk+6HzQmWFjB/yR8W7e0RCMsRMvU3qh6qKzGRAMetDDWwLOcJm8H46qedJ7bua7qfhOynPlvioAvS9R7n53CsL/ZsdEgSCXuUc1uOObPPzcY=
before_install:
- cd django/congressionaldata
- pip install virtualenv
- virtualenv venv
- source venv/bin/activate
install:
- echo "$LOCAL_POSTGRES_DATABASE_NAME"
- pip install -r requirements.txt
- pip install -r requirements.txt -t lib
- pip install coverage==4.5.1
before_script:
- psql -c "create database ${LOCAL_POSTGRES_DATABASE_NAME};" -U postgres
script:
- coverage run --source='.' manage.py test election_data
- coverage report
after_script:
- deactivate
notifications:
  slack:
    secure: ZMDQ9C8mnbnMFzMycpSArmxOiVpDNEeyvPyK5krlkn3py43XvObyurdZ7ODhinLxKTGR2d84XCz6ot193rvx5r4p6USW2efzrp0c9rWvpdIgNwVomQ7Wu6wREasNcDH+oDRfbdsCwSA8CRKhY2VTHjWhS0b5BAbHvRjBloLi20q9muHuKHd0DAuvN5iQHX9psA+6/efS5AAcCuRxSmpvkD5MP17R6QMixt+vCx8HV97T3c5eeHKnWSmLJLA94uCle47d1YU5LFRSqpAIdf23m7myD7xg/C5USsVy7W1LG6el8rUpTG1ygIxp2p2ZsFaDlW477hIcMAu+vbHJXv2AWOk0BKtF9QJvg6tGqm1fRSZoQCIo5ITLyKQWw0sO7YujGhqKUwy39G2u8Q2Mv2eBFO09PtOPWk6cIMbruia7wkCFb7ZXB6A/RbyxZNwDXlxWHlLAO2k9X0unW7iDVJh8huaHuHsekyrCaLaFeJRGBylPf1HtevFLeLYpRc1ot+UdjYa+OcbGdue4lpv4mtCdIN2IBhtq/IX2rxRz8MqZYuxre/IeRJjeRFBt4B3HRWmo2jdQ/hisFmtjTJ+TYw6V56/r9EkYEmk7CrnB4UjCRr9B2EYf/TdWB6xkOlwwhjBCtVtsZUGkknBx80+iZZjZLvaiEZQuPRhpKjIe7dg87/U=
